#!/bin/bash

# This script updates the .env file with the compiled TON contract codes

# Base64 values from ton/build/*.compiled.json
TON_SOURCE_ESCROW_TEMPLATE="te6cckECFwEABO8AART/APSkE/S88sgLAQIBYgISAgLKAwYC9dTPQ0wMBcbCSXwPg+kAwIscAjk4wMe1E0PpA+kDTB/oA+gDUAdD6QPpA+kDTH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQal41XiRVA2zBwACS8CCRMOLgAtMf0z8xIcABlhAjXwPwIOAyIMAF4wIggQFAAZb8CEALMACljDUMNDwIuAxwAOS8CPgMIQP8vACAc4HCwIBIAgJAN87UTQ+kD6QNMH+gD6ANQw0PpA+kD6QNMf0x/THzBTdqCCCvrwgKAcvvLgdBCaEIkQSBA3EDZeIlUC+CNxyFALzxZQCc8WUAbPFhLLH8sfE8sfychQCM8WUAbPFhLLB1AE+gJQA/oCE8zLH8sHye1UgAbc7UTQ+kD6QNMH+gD6ANQB0PpA+kD6QNMf0x/THzBwUwfHALOOEjEH0x8gxwCzljgH0wcwB5Ew4pE44hBqXjVeJFUDUdvHBfLgagzAAfLgZfgjU8GgvvLgZlUKcoAoAZshQC88WUAnPFlAGzxYSyx/LHxPLH8nIUAjPFlAGzxYSywdQBPoCUAP6AhPMyx/LB8ntVAIBIAwPAvc7UTQ+kD6QNMH+gD6ANQB0PpA+kD6QNMf0x/THzBwUwfHALOOEjEH0x8gxwCzljgH0wcwB5Ew4pE44hBqXjVeJFUDUevHBfLgag3AAvLgZ1IsyAHPFsn5AKvfAbry4GglwACOEnCAEMjLBSnPFiX6AstqyXH7AOMOcIAQgDQ4AanBTAIIQF41FGYAYyMsFKc8WghAF9eEA+gLLH8s/JvoCKs8WKs8WywCCCvrwgPoCywDJcfsAAI7IywUqzxYk+gLLaslx+wAQm1UYc8hQC88WUAnPFlAGzxYSyx/LHxPLH8nIUAjPFlAGzxYSywdQBPoCUAP6AhPMyx/LB8ntVAL1O1E0PpA+kDTB/oA+gDUAdD6QPpA+kDTH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQal41XiRVA1PcxwVT7McFsfLgaSDAAgHAAbHy4Gr4I1MToL7y4HUnwACOEnCAEMjLBSrPFif6AstqyXH7AOMOgEBEAanBTAIIQF41FGYAYyMsFK88WghAF9eEA+gLLH8s/KPoCK88WK88WywCCCvrwgPoCywDJcfsAAJ5RyscFjhJwgBDIywUrzxYl+gLLaslx+wDeVQp0yFALzxZQCc8WUAbPFhLLH8sfE8sfychQCM8WUAbPFhLLB1AE+gJQA/oCE8zLH8sHye1UAgEgExYCASAUFQC5un6u1E0PpA+kDTB/oA+gDUAdD6QPpA+kDTH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQal41XiRVAzJskyHDAgLDARKwkltw4PgjAqC5kXDgf4AJ+40V7UTQ+kD6QNMH+gD6ANQB0PpA+kD6QNMf0x/THzBwUwfHALOOEjEH0x8gxwCzljgH0wcwB5Ew4pE44hBqXjVeJFUDMjMKCQgHBgUEQxOADFvhE/aiaH0gfSBpg/0AfQBqAOh9IH0gfSBpj+mP6Y+YOCmD44BZxwkYg+mPkGOAWcscA+mDmAPImHFInHEINS8arxIqgZqvgag8L4PhgUktuHAA5ADni2T8gFXvgN1ZyLhwP8t7gxtQ=="

TON_DESTINATION_ESCROW_TEMPLATE="te6cckECGgEABUcAART/APSkE/S88sgLAQIBYgITAgLKAwYC9dTPQ0wMBcbCSXwPg+kAwIscAjk4wMe1E0PpA+kDTB/oA+gDUAdD6QPpA0x/TH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQahBpXiVVBWzBwACS8CCRMOLgAtMf0z8xIcABlhAjXwPwIOAyIMAF4wIggQFAAZb8CEALMACljDUMNDwIuAxwAOS8CPgMIQP8vACAc4HCwIBIAgJANU7UTQ+kD6QNMH+gD6ANQw0PpA+kDTH9Mf0x/THzBTdqCCCvrwgKAcvvLgdBCaEIkQSBA2EDVVA/gjcchQC88WUAjPFhTLHxLLH8sfyx/JyFAIzxZQBs8WE8sHWPoCUAP6AhPMyx/LB8ntVIAG3O1E0PpA+kDTB/oA+gDUAdD6QPpA0x/TH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQahBpXiVVBVHcxwXy4GoMwAHy4GX4I1PCoL7y4GZVCnKAKAGDIUAvPFlAIzxYUyx8Syx/LH8sfychQCM8WUAbPFhPLB1j6AlAD+gITzMsfywfJ7VQCASAMEAP3O1E0PpA+kDTB/oA+gDUAdD6QPpA0x/TH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQahBpXiVVBcAC8uBnUk3IAc8WyfkAq98BuvLgaPgjU8KgIqC5l1PKxwXy4GreJ8AA4w9wgBDIywVQDs8WJfoCHYA0ODwAkcIAQyMsFK88WJ/oCy2rJcfsAAGpwUwCCEBeNRRmAGMjLBSvPFoIQBfXhAPoCyx/LPyj6AizPFizPFssAggr68ID6AssAyXH7AAByy2rJcfsAVRlzyFALzxZQCM8WFMsfEssfyx/LH8nIUAjPFlAGzxYTywdY+gJQA/oCE8zLH8sHye1UAvU7UTQ+kD6QNMH+gD6ANQB0PpA+kDTH9Mf0x/THzBwUwfHALOOEjEH0x8gxwCzljgH0wcwB5Ew4pE44hBqEGleJVUFUdzHBfLgaSzAAg3AAR2x8uBq+CNTw6C+8uB1J8AAjhJwgBDIywUqzxYn+gLLaslx+wDjDnCAEMiAREgBqcFMAghAXjUUZgBjIywUrzxaCEAX14QD6Assfyz8o+gIrzxYrzxbLAIIK+vCA+gLLAMlx+wAAgssFLM8WJvoCy2rJcfsAVQp0yFALzxZQCM8WFMsfEssfyx/LH8nIUAjPFlAGzxYTywdY+gJQA/oCE8zLH8sHye1UAgEgFBkCASAVFgC/un6u1E0PpA+kDTB/oA+gDUAdD6QPpA0x/TH9Mf0x8wcFMHxwCzjhIxB9MfIMcAs5Y4B9MHMAeRMOKROOIQahBpXiVVBTU1W2xjIcMCAsMBErCSW3DgAfgjAqC5kXDgf4AgEgFxgAnbWivaiaH0gfSBpg/0AfQBqAOh9IH0gaY/pj+mP6Y+YOCmD44BZxwkYg+mPkGOAWcscA+mDmAPImHFInHEINQg0rxKqgpmaDQyMC4sKignAAu7WS3aiaH0gfSBpg/0AfQBqAOh9IH0gaY/pj+mP6Y+YOCmD44BZxwkYg+mPkGOAWcscA+mDmAPImHFInHEINQg0rxKqgrZCGgHhgUmvgbhwAXwRgVApAdApCd8BXNhAAxb4RP2omh9IH0gaYP9AH0AagDofSB9IGmP6Y/pj+mPmDgpg+OAWccJGIPpj5BjgFnLHAPpg5gDyJhxSJxxCDUINK8SqoKbL4IoM6+DYYFJLbhwAOQA54tk/IBV74DdWci4cD/NutsSE="

# Check if .env file exists
if [ ! -f .env ]; then
    echo "❌ .env file not found. Creating from env.example..."
    cp env.example .env
fi

# Update TON_SOURCE_ESCROW_TEMPLATE
if grep -q "^TON_SOURCE_ESCROW_TEMPLATE=" .env; then
    sed -i.bak "s|^TON_SOURCE_ESCROW_TEMPLATE=.*|TON_SOURCE_ESCROW_TEMPLATE=$TON_SOURCE_ESCROW_TEMPLATE|" .env
    echo "✅ Updated TON_SOURCE_ESCROW_TEMPLATE"
else
    echo "TON_SOURCE_ESCROW_TEMPLATE=$TON_SOURCE_ESCROW_TEMPLATE" >> .env
    echo "✅ Added TON_SOURCE_ESCROW_TEMPLATE"
fi

# Update TON_DESTINATION_ESCROW_TEMPLATE
if grep -q "^TON_DESTINATION_ESCROW_TEMPLATE=" .env; then
    sed -i.bak "s|^TON_DESTINATION_ESCROW_TEMPLATE=.*|TON_DESTINATION_ESCROW_TEMPLATE=$TON_DESTINATION_ESCROW_TEMPLATE|" .env
    echo "✅ Updated TON_DESTINATION_ESCROW_TEMPLATE"
else
    echo "TON_DESTINATION_ESCROW_TEMPLATE=$TON_DESTINATION_ESCROW_TEMPLATE" >> .env
    echo "✅ Added TON_DESTINATION_ESCROW_TEMPLATE"
fi

# Clean up backup file
rm -f .env.bak

echo "✅ Done! Your .env file has been updated with the compiled TON contract codes."
echo ""
echo "Note: Make sure you also have these values configured:"
echo "  - TON_ENDPOINT (e.g., https://testnet.toncenter.com/api/v2/jsonRPC)"
echo "  - TON_MNEMONIC (your TON wallet mnemonic)"
echo "  - EVM_RPC_URL (e.g., https://sepolia.infura.io/v3/YOUR-API-KEY)"
echo "  - EVM_MNEMONIC (your EVM wallet mnemonic)"
echo "  - EVM_ESCROW_FACTORY (the deployed escrow factory address)"